// AUTO-GENERATED by scripts/compile-help.ts — do not edit by hand.
// Regenerate: `npx tsx scripts/compile-help.ts` (also runs via `pnpm compile:help` / `pnpm build`).

export const HELP_DOCS: Record<string, { title: string; html: string }> = {};
