// AUTO-GENERATED by scripts/compile-help.ts — do not edit by hand.
// Regenerate: `npx tsx scripts/compile-help.ts` (also runs via `pnpm compile:help` / `pnpm build`).

export const HELP_DOCS: Record<string, { title: string; html: string }> = {
  "attendance": {
    "title": "Marking attendance",
    "html": "<h1>Marking attendance</h1>\n<p>Attendance is marked per class session by the subject teacher or the class teacher.</p>\n<h2>Steps</h2>\n<ol><li>Open <strong>Attendance</strong> from the sidebar.</li><li>Pick the class, section, and date.</li><li>Mark each student <strong>present</strong> or <strong>absent</strong>.</li><li>Save — once a session closes, the record is locked and further changes are audited, not overwritten.</li></ol>\n<p>Students below 75% attendance are flagged automatically on their profile.</p>\n<blockquote class=\"help-screenshot\">Screenshot: the attendance grid for a class session.</blockquote>"
  }
};
